### ISSUE TITLE
Pleromaでのエラー

### ISSUE THREAD

**Issue by xichedelic1337** [yukimochi/Activity-Relay#41]
pleromaでリレーを登録時に

ww:xx:yy.zzz [error] Follower/Following counter update for https://relay.toot.yukimochi.jp/actor failed.
{:error, "id must be a string"}

と出てリレーが機能しない

**Comment by xichedelic1337** [comment]
PleromaのAdmin-feからGUIで設定してもやはり雪餅リレーそのものを認識しないので何か問題があるはず
他のリレー(Fedibirdやmstdn-siteなど)は認識するので雪餅リレーそのものとの相性かもしれない

**Comment by xichedelic1337** [comment]
CLIでの設定やPleromaのブランチを変更などしてみたがやはり動いてくれない
申し訳ないですがこちらでは原因の特定ができません

**Comment by kPherox** [comment]
Pleroma の relay は Follow Activity に `to`/`cc`に `https://www.w3.org/ns/activitystreams#Public` を含んでなくて現状だと Reject が返されてます

ref #22

**Comment by yukimochi** [comment]
Pleroma の採用するリレーのスキームは現状サポート予定がありません。
今後、実装の可能性はありますが優先度は低いです。
