### ISSUE TITLE
DockerDockerは起動できますが、使えません。

### ISSUE THREAD

**Issue by shyamean4151** [yukimochi/Activity-Relay#43]
こんばんは、私はバインディングアドレスを127.1.0.1または0.0.0.0に設定してみましたが、ポートの占有を確認したところ、8051ポートは使用されていませんでした。中継ポートは8051に設定されています。標準の8080ポートを使ってみましたが、使えませんでした。助けてほしいです。

**Comment by shyamean4151** [comment]
何度も試行した後、正しく機能しません。 デプロイできますか？ 私はあなたに支払うことができます。
私はvpsを買い戻しました。
65.21.54.28
root
ehivwX9ahHVhxKjcNFHP
（パスワードをリセットする場合は、16608314151に設定してください。）
どうもありがとうございました、私は今とても忙しいです、展開の準備ができています、教えてください

**Comment by yukimochi** [comment]
資格情報を記載しないでください！
安全のため、投稿を一旦削除しました。

**Comment by shyamean4151** [comment]
正午にwikiを再フォローし、nginxを介してhttps://relay.neko.ciにアクセスできるようになりましたが、https：//relay.neko.ci/inboxを開くことができません（POSTリクエスト用ではありません）が、できますhttps://relay.neko.ci/actorを開きます
