### ISSUE TITLE
Unsure how to follow instances

### ISSUE THREAD

**Issue by augck** [yukimochi/Activity-Relay#46]
I'm sorry but I'm not sure howto follow servers using your software. I want to add other servers to the relay that I can follow it with my own instance but the documentation doesn't seem to describe howto do that. I may have missed it and I would love to be corrected.

Thanks you in advance

**Comment by yukimochi** [comment]
Your question is ...
`How to follow Activity-Relay server from Mastodon, Misskey?`
Is that right?

Sorry for I missed describe that how to do.

How to:
1. Your relay server's endpoint is
`https://<your-server-domain>/inbox`
2. Show relay server config in Mastodon or Misskey and type endpoint address.
3. They can follow relay server.

**Comment by augck** [comment]
I'm trying to follow another instance other than mine. I have instance A, and I'm trying to follow instance B with my relay and get their posts to my instance A. I know that I use the /inbox or /actor endpoint to follow from my instance. I'm trying to follow an instance using my relay who has not tried to follow my relay.

**Comment by yukimochi** [comment]
This relay is designed as community, so relay is always receive follow and do follow-back.
Servers (ex. Mastodon and so on) has their privacy policy and data management policy, so to avoid violating it relay has no follow feature is not implement.
And I don't hear implement accept relay-like follow-request.

**Comment by augck** [comment]
thanks I'll close the issue
