### ISSUE TITLE
Not relaying third-party traffic

### ISSUE THREAD

**Issue by danorton** [yukimochi/Activity-Relay#78]
Everything seems to be running, but it’s only relaying activity from my Mastodon server (4.1.0) that is created locally. Activity that has been relayed from third-party relay servers is ignored.

Am I misunderstanding how this is supposed to work? If so, is there a relay server that will relay *everything*?

**Comment by yukimochi** [comment]
Nesting of relay servers is not assumed. It can also cause an infinite loop.
Depending on the implementation of the other party's relay server, it may be relayed, but in famous implementations, it is determined in various places so that relaying is not easily done.

**Comment by danorton** [comment]
@yukimochi  Thanks.
