### ISSUE TITLE
relay stays stuck as pending

### ISSUE THREAD

**Issue by SeleDreams** [yukimochi/Activity-Relay#85]
Hi, I've tried adding the public relay to my misskey instance (using https://relay.toot.yukimochi.jp/inbox), but it seems to stay stuck as pending, is it normal or not?

**Comment by yukimochi** [comment]
Activity-Relay has a *Manual Approval* feature, so the relay owner may need to approve to resolve the pending status.

**Comment by SeleDreams** [comment]
oh I see, thanks
