### ISSUE TITLE
YUKIMOCHI Activity-Relay製のサーバーが配信元のサーバーブロック設定を貫通してブロック先に配信し続けている可能性がある

### ISSUE THREAD

**Issue by kleuzjatob** [yukimochi/Activity-Relay#99]
弊 Misskey サーバーでブロック中のサーバーの一部に弊サーバーのポストを受信し続けているものが多数見つかりました。
当方で調査したところ、状況証拠ではございますが上記タイトルの可能性が出てきております。
そちらの状況をご確認いただき、可能なら配信しないようご対応いただければ幸いです。

### 弊 Misskey サーバーのバックエンド環境
[misskey-dev/misskey](https://github.com/misskey-dev/misskey/issues)でのチケット発行テンプレートより
```markdown
* Installation Method or Hosting Service: systemd
* Misskey: 2024.7.0
* Node: 20.10.0
* PostgreSQL: 15.2 (Ubuntu 15.2-1.pgdg20.04+1)
* Redis: 7.0.8
* OS and Architecture: Ubuntu 20.04.1 LTS x86_64
```

### ブロック中サーバーへの配信状況
※ リレーＡ：YUKIMOCHI Activity-Relay 製
※ リレーＢ：YUKIMOCHI Activity-Relay 製
※ リレーＣ：[楽しもう。Fediverse。](https://github.com/gittrname/activitypub-relay)
※ 上記3サーバー以外に弊サーバーでのリレー登録なし
| リレーＡに登録 | リレーＢに登録 | リレーＣに登録 | 件数 | 現在の状況 |
| ---- | ---- | ---- | ---- | ---- |
| － | － | － | 9 | 配信停止中を確認 |
| ● | － | － | 2 | ポスト受信中を確認 |
| － | ● | － | 1 | ポスト受信中を確認 |
| ● | ● | － | 0 | （該当なし） |
| － | － | ● | 16 | 配信停止中を確認 |
| ● | － | ● | 0 | （該当なし） |
| － | ● | ● | 3 | ポスト受信中を確認 |
| ● | ● | ● | 1 | ポスト受信中を確認 |

**Comment by yukimochi** [comment]
1. 概要
  
    Activity-Relay を利用したリレーサービスは、本文を含む投稿の転送を行います。
    したがって、 Activity-Relay に送信された投稿は、その利用者のサーバーにそのまま転送されてしまいます。
    転送を望まないサーバーが含まれる Activity-Relay には参加しないことを推奨します。

2. 一部のリレー実装ではブロックが機能しているように見える理由

    一部のリレー実装では投稿の本文を転送するのではなく、元投稿の参照情報を送信しているものがあります。その場合、参照情報を受け取ったサーバーが元の投稿を取得する必要があり、その際に元投稿を持つサーバーのブロック設定が機能していると考えられます。（参照情報を受け取ったサーバーが正直に自身のサーバー情報を GET リクエスト内で申告していることが前提です）
    この実装は、元投稿のサーバーへのアクセスが大量に発生しスケールできないことから Activity-Relay ではこの手法を使わないと受けとれない利用者 (Pleroma) のみに利用されています。

3. Activity-Relay で投稿ごとの配送先カスタマイズは現実的ではなく、実装は困難です。

    各利用者・各実装のブロックリストを把握し転送をハンドリングすることは困難です。また、リレーに参加できる実装では一般的に何らかの抜け道を使えば投稿の取得は可能なはずで、厳密にブロックすることは不可能です。リレーが転送する投稿はすべて宛先が、 `as#Public` (全世界に公開) のものだけですので、リレーによる再配信を防ぎたい投稿は公開投稿にしないということもできます。
    今回調査いただいたような、参照情報を転送する方式のリレーにのみ参加するというのも１つの方法かと思います。

この度はご希望に添えず申し訳ありませんが、より配送管理をカスタマイズできるようなリレーの機能拡張については関心を持っており、同等機能を実現できるようなものは実装するかもしれません。

今回は Activity-Relay についてご関心をいただき、ご連絡いただきありがとうございました。

**Comment by kleuzjatob** [comment]
ご説明ありがとうございます。
一口にリレーと言っても実装方法が複数在り、本件の調査結果は方法の違いによる仕様との事で承知いたしました（確かに今までチケットが無かった事を疑問に思いつつ記入しておりました）。

参加するリレーサーバーは何度か組み替えてはいるものの、YUKIMOCHI Activity-Relay 製の単位では弊サーバー開設時から今日まで長年お世話になっており、転送したくないサーバーが生じたのはつい最近の事でございます。
それが表に記入した一番下となりますが、現状1件という特異性から別な対処法を検討し、リレーサーバーを軒並み外す事は最終手段として進める様にいたします。

当方としては不具合でないと分かり改修を必達で求めるものでは無くなりましたので、本チケットは必要ならクローズいただいて大丈夫です。
この度はご返答いただきありがとうございます。
